Intiate the index.html basic structure
fmanimashaun/Conference-page pull request #1
Opened 2022-10-24 22:28 UTC by fmanimashaun

2022-10-29 21:04 UTC, codecaiine requested changes
Hi @fmanimashaun, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good UI design :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Professinal Repo :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 21:04 UTC, codecaiine commented on index.html
> +					<img src="img/theme_home.png" alt="Creative commons global summit 2015 banner" class="hero__img">
- [x] Good job so far :clap:  I would like to recommend using an `h1` tag for this headline title instead of an image. It is important to use headings to show the document structure.` <h1> `headings should be used for the main heading. Please fix it :smile:

2022-10-29 21:04 UTC, codecaiine commented on components/about.html
> +							class="hero__img mobile">
- [x] Good job so far :clap:  I would like to recommend using an `h1` tag for this headline title instead of an image. It is important to use headings to show the document structure.` <h1> `headings should be used for the main heading. Please use `<h1>` tag for the main title and `hx` tag different from  h1 for other title  :smile:

2022-10-29 21:04 UTC, codecaiine commented on index.html
> +			</section>
- [x] From the project requires the speaker's section should be created dynamically in JavaScript and you should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically. Please create a javascript array of objects to store your speaker's informations and use a javascript code to load it dynamically in order to make your project work as expected :+1: 

#### Example
```
const cards = [
{

  img: 'img/speaker1.png',
  name: 'Speaker Name 1',
  title: 'full-stack developer',
  description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. ',

},

{

  img: 'img/speaker2.png',
  name: 'Speaker Name 2',
  title: 'full-stack developer',
  description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. ',

},
.....
]

```

```
  cards.forEach((card) => {
    result += `
      <div class="contributors-bio-container">
      <div>
        <img src="${card.img}">
      </div>
      <div>
        <h3 class="fw">${card.name}</h3>
        <h3 class="card">${card.title}</h3>
        <div class="title"></div>
        <p class="card-description">${card.description}</p>
      </div>
    </div>`;
  });
```

2022-10-29 21:04 UTC, codecaiine commented on README.md
> +[cc-by-nc-sa-shield]: https://img.shields.io/badge/License-CC%20BY--NC--SA%204.0-lightgrey.svg
- [ ] Great job with your readme very descriptive :+1:  but some of the image links are broken. Please fix them in order to make your readme professional. :smile: 
- [ ] Good job but the link to your live demo is also broken, please make sure to make the live demo available in your readme to make it more professional :+1: 
- [ ] For this capstone project, it is required to record a video presenting your project. I can't find it :cry: . Please record a maximum length of 5 minutes with:
 - A description of the project.
-  A demo of the project features (different pages and different screen sizes).
- highlight some interesting piece of code or something you built that you are very proud of as required for this project :smile:

2022-10-29 22:24 UTC, fmanimashaun commented on index.html
> +					<img src="img/theme_home.png" alt="Creative commons global summit 2015 banner" class="hero__img">
Thanks for the recommendation! it has been replaced with an ```h1``` element as recommended
![index-header](https://user-images.githubusercontent.com/22054464/198854554-7dae6bf4-58f5-4569-8678-30a1ae5c797f.png)

2022-10-29 22:26 UTC, fmanimashaun commented on components/about.html
> +							class="hero__img mobile">
Thanks for the recommendation! it has been replaced with an ```h1``` element as recommended
![about-header](https://user-images.githubusercontent.com/22054464/198854623-d696d9a9-a0ab-4b43-9b80-6f3c8c343638.png)

2022-10-29 22:56 UTC, fmanimashaun commented on README.md
> +[cc-by-nc-sa-shield]: https://img.shields.io/badge/License-CC%20BY--NC--SA%204.0-lightgrey.svg
Thanks for pointing those out, it has been fixed in the readme file accordingly

![image](https://user-images.githubusercontent.com/22054464/198855414-82f30c16-1a1f-4f7e-83f9-efe41bcdbc1f.png)

2022-10-30 00:31 UTC, fmanimashaun commented on index.html
> +			</section>
Thanks for the recommendation! I have created the speaker's section dynamically in JavaScript as recommended!

![image](https://user-images.githubusercontent.com/22054464/198857411-ccae6ece-1c37-44b1-81f2-a813cb7851d0.png)

2022-10-30 00:49 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @fmanimashaun, 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Good commit messages 👍 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-30 00:50 UTC, merged